sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stergiosk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stergiosk/docker-react npm run test
